### ISSUE TITLE
Copy/rename a node

### ISSUE THREAD

**Issue by dsfranzi** [elkozmon/zoonavigator-web#3]
The ability to copy or rename a node in ZooNavigator would be really nice.
At the moment, i would have to do this via creating a new node, copying the content and deleting the old node.

**Comment by elkozmon** [comment]
Yeah I too feel like this should be implemented. It's an easy task but I need to figure out where to put it in the UI so if you have any ideas feel free to share. :) I will start working on it once I have a bit more time on my hands.

**Comment by dsfranzi** [comment]
ZooNavigator already has checkboxes at the side of a node. Maybe in that menu ;)
